#ifndef __PORT_H__
#define __PORT_H__

#include "Main.h"

/* Leds' pins */
#define MOTOR_PORT_DR   (GPIO_PORT2_DATA)
#define MOTOR_PORT_CR   (GPIO_PORT2_DIRECTION)
#define MOTOR_PIN       (GPIO_PIN_0)

#define MOVING_PORT_DR   (GPIO_PORT2_DATA)
#define MOVING_PORT_CR   (GPIO_PORT2_DIRECTION)
#define MOVING_PIN       (GPIO_PIN_1)

#define OPEN_LED_PORT_DR   (GPIO_PORT2_DATA)
#define OPEN_LED_PORT_CR   (GPIO_PORT2_DIRECTION)
#define OPEN_LED_PIN       (GPIO_PIN_2)

#define ALARM_PORT_DR   (GPIO_PORT2_DATA)
#define ALARM_PORT_CR   (GPIO_PORT2_DIRECTION)
#define ALARM_PIN       (GPIO_PIN_3)

#define FLOOR_0_SWITCH_PORT_DR   (GPIO_PORT1_DATA)
#define FLOOR_0_SWITCH_PORT_CR   (GPIO_PORT1_DIRECTION)
#define FLOOR_0_SWITCH_PIN       (GPIO_PIN_1)

#define FLOOR_1_SWITCH_PORT_DR   (GPIO_PORT1_DATA)
#define FLOOR_1_SWITCH_PORT_CR   (GPIO_PORT1_DIRECTION)
#define FLOOR_1_SWITCH_PIN       (GPIO_PIN_2)

#define FLOOR_2_SWITCH_PORT_DR   (GPIO_PORT1_DATA)
#define FLOOR_2_SWITCH_PORT_CR   (GPIO_PORT1_DIRECTION)
#define FLOOR_2_SWITCH_PIN       (GPIO_PIN_3)

#define FLOOR_3_SWITCH_PORT_DR   (GPIO_PORT1_DATA)
#define FLOOR_3_SWITCH_PORT_CR   (GPIO_PORT1_DIRECTION)
#define FLOOR_3_SWITCH_PIN       (GPIO_PIN_4)

#define FLOOR_4_SWITCH_PORT_DR   (GPIO_PORT1_DATA)
#define FLOOR_4_SWITCH_PORT_CR   (GPIO_PORT1_DIRECTION)
#define FLOOR_4_SWITCH_PIN       (GPIO_PIN_5)

#define UP_SWITCH_PORT_DR        (GPIO_PORT1_DATA)
#define UP_SWITCH_PORT_CR        (GPIO_PORT1_DIRECTION)
#define UP_SWITCH_PIN            (GPIO_PIN_6)

#define DOWN_SWITCH_PORT_DR      (GPIO_PORT1_DATA)
#define DOWN_SWITCH_PORT_CR      (GPIO_PORT1_DIRECTION)
#define DOWN_SWITCH_PIN          (GPIO_PIN_7)

#define OPEN_SWITCH_PORT_DR      (GPIO_PORT2_DATA)
#define OPEN_SWITCH_PORT_CR      (GPIO_PORT1_DIRECTION)
#define OPEN_SWITCH_PIN          (GPIO_PIN_0)

#define INCREASE_SWITCH_PORT_DR      (GPIO_PORT2_DATA)
#define INCREASE_SWITCH_PORT_CR      (GPIO_PORT2_DIRECTION)
#define INCREASE_SWITCH_PIN          (GPIO_PIN_4)

#define DECREASE_SWITCH_PORT_DR      (GPIO_PORT2_DATA)
#define DECREASE_SWITCH_PORT_CR      (GPIO_PORT2_DIRECTION)
#define DECREASE_SWITCH_PIN          (GPIO_PIN_5)

#define SEVEN_SEGMENT_DATA_PORT           GPIO_PORT0_DATA
#define SEVEN_SEGMENT_DIR_PORT            GPIO_PORT0_DIRECTION
#define SEVEN_SEGMENT_ENABLE_DATA_PORT    GPIO_PORT1_DATA
#define SEVEN_SEGMENT_ENABLE_DIR_PORT     GPIO_PORT1_DIRECTION
#define SEVEN_SEGMENT_ENABLE_PIN          GPIO_PIN_0

char numbers[] = {0x0C0, 0x0F9, 0x0A4, 0x0B0, 0x99, 0x92, 0x82, 0x0F8, 0x80, 0x90};


/* End of code filling */
#endif // __PORT_H__
