#ifndef __PORT_H__
#define __PORT_H__

#include "Main.h"

/* Leds' pins */
#define MOTOR_PORT_DR   (GPIO_PORT2_DATA)
#define MOTOR_PORT_CR   (GPIO_PORT2_DIRECTION)
#define MOTOR_PIN       (GPIO_PIN_0)

#define FLOOR_0_SWITCH_PORT_DR   (GPIO_PORT1_DATA)
#define FLOOR_0_SWITCH_PORT_CR   (GPIO_PORT1_DIRECTION)
#define FLOOR_0_SWITCH_PIN       (GPIO_PIN_1)

#define FLOOR_1_SWITCH_PORT_DR   (GPIO_PORT1_DATA)
#define FLOOR_1_SWITCH_PORT_CR   (GPIO_PORT1_DIRECTION)
#define FLOOR_1_SWITCH_PIN       (GPIO_PIN_2)

#define FLOOR_2_SWITCH_PORT_DR   (GPIO_PORT1_DATA)
#define FLOOR_2_SWITCH_PORT_CR   (GPIO_PORT1_DIRECTION)
#define FLOOR_2_SWITCH_PIN       (GPIO_PIN_3)

#define FLOOR_3_SWITCH_PORT_DR   (GPIO_PORT1_DATA)
#define FLOOR_3_SWITCH_PORT_CR   (GPIO_PORT1_DIRECTION)
#define FLOOR_3_SWITCH_PIN       (GPIO_PIN_4)

#define FLOOR_4_SWITCH_PORT_DR   (GPIO_PORT1_DATA)
#define FLOOR_4_SWITCH_PORT_CR   (GPIO_PORT1_DIRECTION)
#define FLOOR_4_SWITCH_PIN       (GPIO_PIN_5)

#define UP_SWITCH_PORT_DR        (GPIO_PORT1_DATA)
#define UP_SWITCH_PORT_CR        (GPIO_PORT1_DIRECTION)
#define UP_SWITCH_PIN            (GPIO_PIN_6)

#define DOWN_SWITCH_PORT_DR      (GPIO_PORT1_DATA)
#define DOWN_SWITCH_PORT_CR      (GPIO_PORT1_DIRECTION)
#define DOWN_SWITCH_PIN          (GPIO_PIN_7)


/* End of code filling */
#endif // __PORT_H__
